pull_request_rules:
  - name: Automatic merge if the author is halildurmus and CI passes
    conditions:
      - author=halildurmus
      - status-success=test
      - status-success=build
      - label!=work-in-progress
    actions:
      merge:
        method: merge
      delete_head_branch: {}


  - name: Automatic merge when reviewed and CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=test
      - status-success=build
      - label!=work-in-progress
    actions:
      merge:
        method: merge
      delete_head_branch: {}


  - name: Automatic merge when AutoMerge label added and CI passes
    conditions:
      - status-success=test
      - status-success=build
      - label=AutoMerge
      - label!=work-in-progress
    actions:
      merge:
        method: merge
      delete_head_branch: {}
